"""initial_schema

Revision ID: 0044cbef2700
Revises: None
Create Date: 2026-07-29 20:13:50.141379

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0044cbef2700"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "adversarial_validator_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("max_steps", sa.Integer(), nullable=False),
        sa.Column("min_severity", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("end_scan_max_concurrent", sa.Integer(), nullable=False),
        sa.Column("auto_validate_inline", sa.Boolean(), nullable=False),
        sa.Column("require_concrete_disproof", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "api_collection",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("base_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("servers", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("scope_hosts", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "auth_summary_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("readiness_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("api_collection", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_api_collection_name"), ["name"], unique=True
        )

    op.create_table(
        "burp_rest_api_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("api_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("api_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "scan_configuration_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("scan_sqli", sa.Boolean(), nullable=False),
        sa.Column("scan_xss", sa.Boolean(), nullable=False),
        sa.Column("scan_command_injection", sa.Boolean(), nullable=False),
        sa.Column("scan_path_traversal", sa.Boolean(), nullable=False),
        sa.Column("scan_ssrf", sa.Boolean(), nullable=False),
        sa.Column("scan_xxe", sa.Boolean(), nullable=False),
        sa.Column("scan_ssti", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cloudflare_access_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("audience", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "crawler_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("js_endpoint_discovery_enabled", sa.Boolean(), nullable=False),
        sa.Column("skip_dangerous_actions", sa.Boolean(), nullable=False),
        sa.Column("suppress_form_submit_actions", sa.Boolean(), nullable=False),
        sa.Column(
            "block_non_idempotent_interactive_replay", sa.Boolean(), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "global_http_header_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("headers_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "header_name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True
        ),
        sa.Column(
            "header_value", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "llm_provider_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("api_format", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("api_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("base_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("models_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("max_tpm", sa.Integer(), nullable=True),
        sa.Column("max_rpm", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("llm_provider_config", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_llm_provider_config_name"), ["name"], unique=False
        )

    op.create_table(
        "phase_checkpoint",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("phase", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "idempotency_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("data_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("phase_checkpoint", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_phase_checkpoint_idempotency_key"),
            ["idempotency_key"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_phase_checkpoint_phase"), ["phase"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_phase_checkpoint_run_id"), ["run_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_phase_checkpoint_run_kind"), ["run_kind"], unique=False
        )

    op.create_table(
        "reporting_debug_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("capture_enabled", sa.Boolean(), nullable=False),
        sa.Column("panel_enabled", sa.Boolean(), nullable=False),
        sa.Column("batch_max_concurrent", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scan_lead",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("collection_id", sa.Integer(), nullable=True),
        sa.Column(
            "producer_run_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("producer_run_id", sa.Integer(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("severity", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("location", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("evidence", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "investigated_by_run_type",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column("investigated_by_run_id", sa.Integer(), nullable=True),
        sa.Column("linked_finding_id", sa.Integer(), nullable=True),
        sa.Column(
            "imported_into_run_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("imported_into_run_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scan_lead", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_scan_lead_collection_id"), ["collection_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_scan_lead_imported_into_run_id"),
            ["imported_into_run_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_scan_lead_imported_into_run_type"),
            ["imported_into_run_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_scan_lead_producer_run_id"),
            ["producer_run_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_scan_lead_producer_run_type"),
            ["producer_run_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_scan_lead_source"), ["source"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_scan_lead_status"), ["status"], unique=False
        )

    op.create_table(
        "scan_obligation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("scan_mode", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("owasp_catalog", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("owasp_category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "vulnerability_technique",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.Column("route_template", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("http_method", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("parameter", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "required_identity_comparison",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "exemption_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scan_obligation", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_scan_obligation_owasp_category"),
            ["owasp_category"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_scan_obligation_route_template"),
            ["route_template"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_scan_obligation_run_id"), ["run_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_scan_obligation_run_kind"), ["run_kind"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_scan_obligation_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_scan_obligation_vulnerability_technique"),
            ["vulnerability_technique"],
            unique=False,
        )

    op.create_table(
        "scanner_policy",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("execution_monitor_enabled", sa.Boolean(), nullable=False),
        sa.Column("disable_deterministic_checks", sa.Boolean(), nullable=False),
        sa.Column("max_consecutive_text_turns", sa.Integer(), nullable=False),
        sa.Column("enforce_full_coverage_obligations", sa.Boolean(), nullable=False),
        sa.Column("scan_mode", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("max_probes_per_page", sa.Integer(), nullable=False),
        sa.Column("thinking_max_steps", sa.Integer(), nullable=False),
        sa.Column("request_timeout_s", sa.Float(), nullable=False),
        sa.Column("min_delay_s", sa.Float(), nullable=False),
        sa.Column("max_request_body_bytes", sa.Integer(), nullable=False),
        sa.Column("response_body_read_limit_bytes", sa.Integer(), nullable=False),
        sa.Column(
            "allowed_schemes", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "methods_by_mode", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "blocked_headers", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("follow_redirects", sa.Boolean(), nullable=False),
        sa.Column("allow_subdomains", sa.Boolean(), nullable=False),
        sa.Column("require_approval_for_destructive", sa.Boolean(), nullable=False),
        sa.Column("strict_locator_enforcement", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "site",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("base_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("requires_auth", sa.Boolean(), nullable=False),
        sa.Column("login_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("scan_guidance", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("scope_hosts", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("site", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_site_name"), ["name"], unique=True)

    op.create_table(
        "specialist_agent_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("max_concurrent", sa.Integer(), nullable=False),
        sa.Column("max_steps", sa.Integer(), nullable=False),
        sa.Column("min_priority", sa.Integer(), nullable=False),
        sa.Column("dispatch_idor", sa.Boolean(), nullable=False),
        sa.Column("dispatch_auth_bypass", sa.Boolean(), nullable=False),
        sa.Column("dispatch_sqli", sa.Boolean(), nullable=False),
        sa.Column("dispatch_xss", sa.Boolean(), nullable=False),
        sa.Column("dispatch_business_logic", sa.Boolean(), nullable=False),
        sa.Column("dispatch_ssrf", sa.Boolean(), nullable=False),
        sa.Column("dispatch_path_traversal", sa.Boolean(), nullable=False),
        sa.Column("dispatch_cors", sa.Boolean(), nullable=False),
        sa.Column("dispatch_crypto", sa.Boolean(), nullable=False),
        sa.Column("dispatch_config", sa.Boolean(), nullable=False),
        sa.Column("dispatch_file_upload", sa.Boolean(), nullable=False),
        sa.Column("trigger_specialist_on_burp", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "upstream_proxy_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("proxy_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("proxy_scanner", sa.Boolean(), nullable=False),
        sa.Column("proxy_llm", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "api_document",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("collection_id", sa.Integer(), nullable=False),
        sa.Column("filename", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("doc_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("stored_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["api_collection.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("api_document", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_api_document_collection_id"), ["collection_id"], unique=False
        )

    op.create_table(
        "credential",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "login_fields_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("login_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("auth_mode", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("totp_seed", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "test_mailbox_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["site.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("credential", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_credential_site_id"), ["site_id"], unique=False
        )

    op.create_table(
        "llm_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("provider_id", sa.Integer(), nullable=True),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("api_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("base_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("max_tokens", sa.Integer(), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=True),
        sa.Column("use_vision", sa.Boolean(), nullable=False),
        sa.Column("force_tool_choice", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["llm_provider_config.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("llm_config", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_llm_config_is_active"), ["is_active"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_llm_config_name"), ["name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_llm_config_provider_id"), ["provider_id"], unique=False
        )

    op.create_table(
        "api_endpoint",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("collection_id", sa.Integer(), nullable=False),
        sa.Column("source_doc_id", sa.Integer(), nullable=True),
        sa.Column("method", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("base_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("operation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "parameters_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "request_body_schema_json",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.Column(
            "response_schema_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("security_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("auth_required", sa.Boolean(), nullable=False),
        sa.Column("tags_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "sample_request_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("in_scope", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("prereq_can_test", sa.Boolean(), nullable=False),
        sa.Column("prereq_can_test_auth", sa.Boolean(), nullable=False),
        sa.Column("prereq_notes", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["api_collection.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_doc_id"],
            ["api_document.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("api_endpoint", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_api_endpoint_collection_id"), ["collection_id"], unique=False
        )

    op.create_table(
        "llm_profile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("default_model_id", sa.Integer(), nullable=True),
        sa.Column(
            "role_models_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["default_model_id"],
            ["llm_config.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("llm_profile", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_llm_profile_is_active"), ["is_active"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_llm_profile_name"), ["name"], unique=False)

    op.create_table(
        "api_credential",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("collection_id", sa.Integer(), nullable=False),
        sa.Column("scheme", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("scope", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("endpoint_id", sa.Integer(), nullable=True),
        sa.Column("auth_endpoint", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["api_collection.id"],
        ),
        sa.ForeignKeyConstraint(
            ["endpoint_id"],
            ["api_endpoint.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("api_credential", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_api_credential_collection_id"),
            ["collection_id"],
            unique=False,
        )

    op.create_table(
        "api_test_run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("collection_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("llm_config_id", sa.Integer(), nullable=True),
        sa.Column("llm_profile_id", sa.Integer(), nullable=True),
        sa.Column("coverage_mode", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "recon_summary_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "token_usage_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "phase", sa.String(), server_default=sa.text("'created'"), nullable=False
        ),
        sa.Column("outcome", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("terminal_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sast_run_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("waf_provider", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("waf_confidence", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("waf_evidence", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["api_collection.id"],
        ),
        sa.ForeignKeyConstraint(
            ["llm_config_id"],
            ["llm_config.id"],
        ),
        sa.ForeignKeyConstraint(
            ["llm_profile_id"],
            ["llm_profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("api_test_run", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_api_test_run_collection_id"), ["collection_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_api_test_run_sast_run_id"), ["sast_run_id"], unique=False
        )

    op.create_table(
        "sast_run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("collection_id", sa.Integer(), nullable=True),
        sa.Column("document_id", sa.Integer(), nullable=True),
        sa.Column(
            "source_archive_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("source_filename", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "triggered_by_run_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("triggered_by_run_id", sa.Integer(), nullable=True),
        sa.Column("llm_config_id", sa.Integer(), nullable=True),
        sa.Column("llm_profile_id", sa.Integer(), nullable=True),
        sa.Column("leads_count", sa.Integer(), nullable=False),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "token_usage_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["api_collection.id"],
        ),
        sa.ForeignKeyConstraint(
            ["llm_config_id"],
            ["llm_config.id"],
        ),
        sa.ForeignKeyConstraint(
            ["llm_profile_id"],
            ["llm_profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sast_run", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sast_run_collection_id"), ["collection_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_sast_run_document_id"), ["document_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_sast_run_triggered_by_run_id"),
            ["triggered_by_run_id"],
            unique=False,
        )

    op.create_table(
        "test_run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("use_screenshots", sa.Boolean(), nullable=False),
        sa.Column("max_depth", sa.Integer(), nullable=False),
        sa.Column("max_pages", sa.Integer(), nullable=False),
        sa.Column(
            "crawler_mode", sa.String(), server_default=sa.text("'url'"), nullable=False
        ),
        sa.Column("scan_mode", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "scanner_policy_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("pages_discovered", sa.Integer(), nullable=False),
        sa.Column("current_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "per_user_progress", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("llm_config_id", sa.Integer(), nullable=True),
        sa.Column("llm_profile_id", sa.Integer(), nullable=True),
        sa.Column("recon_summary", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "token_usage_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "execution_snapshot_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "scan_metrics_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "coverage_mode",
            sa.String(),
            server_default=sa.text("'track'"),
            nullable=False,
        ),
        sa.Column(
            "phase", sa.String(), server_default=sa.text("'created'"), nullable=False
        ),
        sa.Column("outcome", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("terminal_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("waf_provider", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("waf_confidence", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("waf_evidence", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("crawl_credential_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["crawl_credential_id"],
            ["credential.id"],
        ),
        sa.ForeignKeyConstraint(
            ["llm_config_id"],
            ["llm_config.id"],
        ),
        sa.ForeignKeyConstraint(
            ["llm_profile_id"],
            ["llm_profile.id"],
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["site.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("test_run", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_test_run_site_id"), ["site_id"], unique=False
        )

    op.create_table(
        "agent_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("test_run_id", sa.Integer(), nullable=False),
        sa.Column("run_kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("agent_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("current_task", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("outcome", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["test_run_id"],
            ["test_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agent_log", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_agent_log_agent_id"), ["agent_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_agent_log_run_kind"), ["run_kind"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_agent_log_test_run_id"), ["test_run_id"], unique=False
        )

    op.create_table(
        "alice_chat_session",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("test_run_id", sa.Integer(), nullable=False),
        sa.Column("run_kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("session_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["test_run_id"],
            ["test_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("alice_chat_session", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_alice_chat_session_run_kind"), ["run_kind"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_alice_chat_session_session_key"),
            ["session_key"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_alice_chat_session_test_run_id"),
            ["test_run_id"],
            unique=False,
        )

    op.create_table(
        "api_endpoint_test",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("api_test_run_id", sa.Integer(), nullable=False),
        sa.Column("endpoint_id", sa.Integer(), nullable=False),
        sa.Column(
            "owasp_api_category", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("skip_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "finding_ids_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("last_updated", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["api_test_run_id"],
            ["api_test_run.id"],
        ),
        sa.ForeignKeyConstraint(
            ["endpoint_id"],
            ["api_endpoint.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("api_endpoint_test", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_api_endpoint_test_api_test_run_id"),
            ["api_test_run_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_api_endpoint_test_endpoint_id"),
            ["endpoint_id"],
            unique=False,
        )

    op.create_table(
        "crawled_page",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("test_run_id", sa.Integer(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("state_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("state_label", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("state_kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "replay_steps_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("page_text", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("screenshot_b64", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("llm_context", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("in_scope", sa.Boolean(), nullable=False),
        sa.Column("scan_status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("req_auth", sa.Boolean(), nullable=True),
        sa.Column("takes_input", sa.Boolean(), nullable=True),
        sa.Column("has_object_ref", sa.Boolean(), nullable=True),
        sa.Column("has_business_logic", sa.Boolean(), nullable=True),
        sa.Column("accessible_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "owasp_applicable_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("discovered_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["test_run_id"],
            ["test_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("crawled_page", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_crawled_page_state_key"), ["state_key"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_crawled_page_test_run_id"), ["test_run_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_crawled_page_url"), ["url"], unique=False)

    op.create_table(
        "scan_checkpoint",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("test_run_id", sa.Integer(), nullable=False),
        sa.Column("messages_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("history_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "blocked_urls_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "failed_url_counts_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("step_count", sa.Integer(), nullable=False),
        sa.Column("progressive_findings_count", sa.Integer(), nullable=False),
        sa.Column("consecutive_context_tools", sa.Integer(), nullable=False),
        sa.Column(
            "completion_state_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["test_run_id"],
            ["test_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scan_checkpoint", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_scan_checkpoint_test_run_id"), ["test_run_id"], unique=True
        )

    op.create_table(
        "scan_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("test_run_id", sa.Integer(), nullable=False),
        sa.Column("run_kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("phase", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("message", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("page_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("data_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["test_run_id"],
            ["test_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scan_log", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_scan_log_run_kind"), ["run_kind"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_scan_log_test_run_id"), ["test_run_id"], unique=False
        )

    op.create_table(
        "scanner_session",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("test_run_id", sa.Integer(), nullable=False),
        sa.Column("run_kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("account_label", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("credential_id", sa.Integer(), nullable=True),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cookies_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "extra_headers_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "session_metadata", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("token_hint", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "token_fingerprint", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "lifecycle_state", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("validation_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_status", sa.Integer(), nullable=True),
        sa.Column("last_validated_at", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["credential_id"],
            ["credential.id"],
        ),
        sa.ForeignKeyConstraint(
            ["test_run_id"],
            ["test_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scanner_session", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_scanner_session_account_label"),
            ["account_label"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_scanner_session_credential_id"),
            ["credential_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_scanner_session_is_active"), ["is_active"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_scanner_session_kind"), ["kind"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_scanner_session_label"), ["label"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_scanner_session_lifecycle_state"),
            ["lifecycle_state"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_scanner_session_run_kind"), ["run_kind"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_scanner_session_test_run_id"), ["test_run_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_scanner_session_token_fingerprint"),
            ["token_fingerprint"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_scanner_session_username"), ["username"], unique=False
        )

    op.create_table(
        "target_intel_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("test_run_id", sa.Integer(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("method", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("evidence", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("item_metadata", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("discovered_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["test_run_id"],
            ["test_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("target_intel_item", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_target_intel_item_key"), ["key"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_target_intel_item_kind"), ["kind"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_target_intel_item_test_run_id"),
            ["test_run_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_target_intel_item_url"), ["url"], unique=False
        )

    op.create_table(
        "traffic_entry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("test_run_id", sa.Integer(), nullable=False),
        sa.Column("api_test_run_id", sa.Integer(), nullable=True),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("method", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "request_headers", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("request_body", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sa.Integer(), nullable=True),
        sa.Column(
            "response_headers", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("response_body", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["test_run_id"],
            ["test_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("traffic_entry", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_traffic_entry_api_test_run_id"),
            ["api_test_run_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_traffic_entry_test_run_id"), ["test_run_id"], unique=False
        )

    op.create_table(
        "alice_chat_message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("message_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sender", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("step_data_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ts", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["alice_chat_session.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("alice_chat_message", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_alice_chat_message_message_key"),
            ["message_key"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_alice_chat_message_session_id"), ["session_id"], unique=False
        )

    op.create_table(
        "page_credential_view",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("page_id", sa.Integer(), nullable=False),
        sa.Column("test_run_id", sa.Integer(), nullable=False),
        sa.Column("credential_id", sa.Integer(), nullable=True),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("screenshot_b64", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("llm_context", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("page_text", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("req_auth", sa.Boolean(), nullable=True),
        sa.Column("takes_input", sa.Boolean(), nullable=True),
        sa.Column("has_object_ref", sa.Boolean(), nullable=True),
        sa.Column("has_business_logic", sa.Boolean(), nullable=True),
        sa.Column(
            "owasp_applicable_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["page_id"],
            ["crawled_page.id"],
        ),
        sa.ForeignKeyConstraint(
            ["test_run_id"],
            ["test_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("page_credential_view", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_page_credential_view_page_id"), ["page_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_page_credential_view_test_run_id"),
            ["test_run_id"],
            unique=False,
        )

    op.create_table(
        "page_link",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("test_run_id", sa.Integer(), nullable=False),
        sa.Column("source_page_id", sa.Integer(), nullable=False),
        sa.Column("target_page_id", sa.Integer(), nullable=True),
        sa.Column("target_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("link_text", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("action_kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "action_data_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["source_page_id"],
            ["crawled_page.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_page_id"],
            ["crawled_page.id"],
        ),
        sa.ForeignKeyConstraint(
            ["test_run_id"],
            ["test_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("page_link", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_page_link_source_page_id"), ["source_page_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_page_link_test_run_id"), ["test_run_id"], unique=False
        )

    op.create_table(
        "page_owasp_test",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("test_run_id", sa.Integer(), nullable=False),
        sa.Column("page_id", sa.Integer(), nullable=False),
        sa.Column("owasp_category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("skip_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "finding_ids_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "test_classes_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["page_id"],
            ["crawled_page.id"],
        ),
        sa.ForeignKeyConstraint(
            ["test_run_id"],
            ["test_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("page_owasp_test", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_page_owasp_test_page_id"), ["page_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_page_owasp_test_test_run_id"), ["test_run_id"], unique=False
        )

    op.create_table(
        "probe_execution",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("obligation_id", sa.Integer(), nullable=False),
        sa.Column("traffic_id", sa.Integer(), nullable=True),
        sa.Column(
            "session_identity", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("payload_preview", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("response_time_ms", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["obligation_id"],
            ["scan_obligation.id"],
        ),
        sa.ForeignKeyConstraint(
            ["traffic_id"],
            ["traffic_entry.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("probe_execution", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_probe_execution_obligation_id"),
            ["obligation_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_probe_execution_run_id"), ["run_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_probe_execution_run_kind"), ["run_kind"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_probe_execution_traffic_id"), ["traffic_id"], unique=False
        )

    op.create_table(
        "scan_finding",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("test_run_id", sa.Integer(), nullable=True),
        sa.Column("page_id", sa.Integer(), nullable=True),
        sa.Column("owasp_category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("severity", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("impact", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("likelihood", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("recommendation", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cvss_score", sa.Float(), nullable=False),
        sa.Column("cvss_vector", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("affected_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("evidence", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "request_evidence", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "response_evidence", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("evidence_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "merged_instances", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("poc_command", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("poc_setup", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("screenshot_b64", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("finding_source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "validation_status", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("validation_note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("api_test_run_id", sa.Integer(), nullable=True),
        sa.Column(
            "owasp_api_category", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["page_id"],
            ["crawled_page.id"],
        ),
        sa.ForeignKeyConstraint(
            ["test_run_id"],
            ["test_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scan_finding", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_scan_finding_api_test_run_id"),
            ["api_test_run_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_scan_finding_finding_source"),
            ["finding_source"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_scan_finding_owasp_api_category"),
            ["owasp_api_category"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_scan_finding_owasp_category"),
            ["owasp_category"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_scan_finding_page_id"), ["page_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_scan_finding_test_run_id"), ["test_run_id"], unique=False
        )

    op.create_table(
        "coverage_evidence",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("execution_id", sa.Integer(), nullable=False),
        sa.Column(
            "expected_behavior", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "observed_behavior", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "evaluation_oracle", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("outcome", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("evidence_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["probe_execution.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("coverage_evidence", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_coverage_evidence_execution_id"),
            ["execution_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("coverage_evidence", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_coverage_evidence_execution_id"))

    op.drop_table("coverage_evidence")
    with op.batch_alter_table("scan_finding", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scan_finding_test_run_id"))
        batch_op.drop_index(batch_op.f("ix_scan_finding_page_id"))
        batch_op.drop_index(batch_op.f("ix_scan_finding_owasp_category"))
        batch_op.drop_index(batch_op.f("ix_scan_finding_owasp_api_category"))
        batch_op.drop_index(batch_op.f("ix_scan_finding_finding_source"))
        batch_op.drop_index(batch_op.f("ix_scan_finding_api_test_run_id"))

    op.drop_table("scan_finding")
    with op.batch_alter_table("probe_execution", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_probe_execution_traffic_id"))
        batch_op.drop_index(batch_op.f("ix_probe_execution_run_kind"))
        batch_op.drop_index(batch_op.f("ix_probe_execution_run_id"))
        batch_op.drop_index(batch_op.f("ix_probe_execution_obligation_id"))

    op.drop_table("probe_execution")
    with op.batch_alter_table("page_owasp_test", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_page_owasp_test_test_run_id"))
        batch_op.drop_index(batch_op.f("ix_page_owasp_test_page_id"))

    op.drop_table("page_owasp_test")
    with op.batch_alter_table("page_link", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_page_link_test_run_id"))
        batch_op.drop_index(batch_op.f("ix_page_link_source_page_id"))

    op.drop_table("page_link")
    with op.batch_alter_table("page_credential_view", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_page_credential_view_test_run_id"))
        batch_op.drop_index(batch_op.f("ix_page_credential_view_page_id"))

    op.drop_table("page_credential_view")
    with op.batch_alter_table("alice_chat_message", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_alice_chat_message_session_id"))
        batch_op.drop_index(batch_op.f("ix_alice_chat_message_message_key"))

    op.drop_table("alice_chat_message")
    with op.batch_alter_table("traffic_entry", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_traffic_entry_test_run_id"))
        batch_op.drop_index(batch_op.f("ix_traffic_entry_api_test_run_id"))

    op.drop_table("traffic_entry")
    with op.batch_alter_table("target_intel_item", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_target_intel_item_url"))
        batch_op.drop_index(batch_op.f("ix_target_intel_item_test_run_id"))
        batch_op.drop_index(batch_op.f("ix_target_intel_item_kind"))
        batch_op.drop_index(batch_op.f("ix_target_intel_item_key"))

    op.drop_table("target_intel_item")
    with op.batch_alter_table("scanner_session", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scanner_session_username"))
        batch_op.drop_index(batch_op.f("ix_scanner_session_token_fingerprint"))
        batch_op.drop_index(batch_op.f("ix_scanner_session_test_run_id"))
        batch_op.drop_index(batch_op.f("ix_scanner_session_run_kind"))
        batch_op.drop_index(batch_op.f("ix_scanner_session_lifecycle_state"))
        batch_op.drop_index(batch_op.f("ix_scanner_session_label"))
        batch_op.drop_index(batch_op.f("ix_scanner_session_kind"))
        batch_op.drop_index(batch_op.f("ix_scanner_session_is_active"))
        batch_op.drop_index(batch_op.f("ix_scanner_session_credential_id"))
        batch_op.drop_index(batch_op.f("ix_scanner_session_account_label"))

    op.drop_table("scanner_session")
    with op.batch_alter_table("scan_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scan_log_test_run_id"))
        batch_op.drop_index(batch_op.f("ix_scan_log_run_kind"))

    op.drop_table("scan_log")
    with op.batch_alter_table("scan_checkpoint", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scan_checkpoint_test_run_id"))

    op.drop_table("scan_checkpoint")
    with op.batch_alter_table("crawled_page", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_crawled_page_url"))
        batch_op.drop_index(batch_op.f("ix_crawled_page_test_run_id"))
        batch_op.drop_index(batch_op.f("ix_crawled_page_state_key"))

    op.drop_table("crawled_page")
    with op.batch_alter_table("api_endpoint_test", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_endpoint_test_endpoint_id"))
        batch_op.drop_index(batch_op.f("ix_api_endpoint_test_api_test_run_id"))

    op.drop_table("api_endpoint_test")
    with op.batch_alter_table("alice_chat_session", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_alice_chat_session_test_run_id"))
        batch_op.drop_index(batch_op.f("ix_alice_chat_session_session_key"))
        batch_op.drop_index(batch_op.f("ix_alice_chat_session_run_kind"))

    op.drop_table("alice_chat_session")
    with op.batch_alter_table("agent_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_log_test_run_id"))
        batch_op.drop_index(batch_op.f("ix_agent_log_run_kind"))
        batch_op.drop_index(batch_op.f("ix_agent_log_agent_id"))

    op.drop_table("agent_log")
    with op.batch_alter_table("test_run", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_test_run_site_id"))

    op.drop_table("test_run")
    with op.batch_alter_table("sast_run", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sast_run_triggered_by_run_id"))
        batch_op.drop_index(batch_op.f("ix_sast_run_document_id"))
        batch_op.drop_index(batch_op.f("ix_sast_run_collection_id"))

    op.drop_table("sast_run")
    with op.batch_alter_table("api_test_run", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_test_run_sast_run_id"))
        batch_op.drop_index(batch_op.f("ix_api_test_run_collection_id"))

    op.drop_table("api_test_run")
    with op.batch_alter_table("api_credential", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_credential_collection_id"))

    op.drop_table("api_credential")
    with op.batch_alter_table("llm_profile", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_llm_profile_name"))
        batch_op.drop_index(batch_op.f("ix_llm_profile_is_active"))

    op.drop_table("llm_profile")
    with op.batch_alter_table("api_endpoint", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_endpoint_collection_id"))

    op.drop_table("api_endpoint")
    with op.batch_alter_table("llm_config", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_llm_config_provider_id"))
        batch_op.drop_index(batch_op.f("ix_llm_config_name"))
        batch_op.drop_index(batch_op.f("ix_llm_config_is_active"))

    op.drop_table("llm_config")
    with op.batch_alter_table("credential", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_credential_site_id"))

    op.drop_table("credential")
    with op.batch_alter_table("api_document", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_document_collection_id"))

    op.drop_table("api_document")
    op.drop_table("upstream_proxy_config")
    op.drop_table("specialist_agent_config")
    with op.batch_alter_table("site", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_site_name"))

    op.drop_table("site")
    op.drop_table("scanner_policy")
    with op.batch_alter_table("scan_obligation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scan_obligation_vulnerability_technique"))
        batch_op.drop_index(batch_op.f("ix_scan_obligation_status"))
        batch_op.drop_index(batch_op.f("ix_scan_obligation_run_kind"))
        batch_op.drop_index(batch_op.f("ix_scan_obligation_run_id"))
        batch_op.drop_index(batch_op.f("ix_scan_obligation_route_template"))
        batch_op.drop_index(batch_op.f("ix_scan_obligation_owasp_category"))

    op.drop_table("scan_obligation")
    with op.batch_alter_table("scan_lead", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scan_lead_status"))
        batch_op.drop_index(batch_op.f("ix_scan_lead_source"))
        batch_op.drop_index(batch_op.f("ix_scan_lead_producer_run_type"))
        batch_op.drop_index(batch_op.f("ix_scan_lead_producer_run_id"))
        batch_op.drop_index(batch_op.f("ix_scan_lead_imported_into_run_type"))
        batch_op.drop_index(batch_op.f("ix_scan_lead_imported_into_run_id"))
        batch_op.drop_index(batch_op.f("ix_scan_lead_collection_id"))

    op.drop_table("scan_lead")
    op.drop_table("reporting_debug_config")
    with op.batch_alter_table("phase_checkpoint", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_phase_checkpoint_run_kind"))
        batch_op.drop_index(batch_op.f("ix_phase_checkpoint_run_id"))
        batch_op.drop_index(batch_op.f("ix_phase_checkpoint_phase"))
        batch_op.drop_index(batch_op.f("ix_phase_checkpoint_idempotency_key"))

    op.drop_table("phase_checkpoint")
    with op.batch_alter_table("llm_provider_config", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_llm_provider_config_name"))

    op.drop_table("llm_provider_config")
    op.drop_table("global_http_header_config")
    op.drop_table("crawler_config")
    op.drop_table("cloudflare_access_config")
    op.drop_table("burp_rest_api_config")
    with op.batch_alter_table("api_collection", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_collection_name"))

    op.drop_table("api_collection")
    op.drop_table("adversarial_validator_config")
    # ### end Alembic commands ###
