export const DEFAULT_SPECIALIST_AGENT_FORM = {
  enabled: true,
  auto_dispatch_enabled: true,
  max_concurrent: 5,
  max_queued: 20,
  max_steps: 30,
  min_priority: 7,
  dispatch_idor: true,
  dispatch_auth_bypass: true,
  dispatch_sqli: true,
  dispatch_xss: true,
  dispatch_business_logic: true,
  dispatch_ssrf: true,
  dispatch_path_traversal: true,
  dispatch_cors: false,
  dispatch_crypto: true,
  dispatch_config: false,
  dispatch_file_upload: true,
  trigger_specialist_on_burp: false,
};
