#!/usr/bin/env python3
"""Generate a combined THIRD_PARTY_LICENSES file for the installed dependencies.

Attribution licenses (MIT/BSD/Apache-2.0/MPL-2.0/...) require that we reproduce
each dependency's copyright notice and license text in any *binary* distribution
we hand out (PyInstaller app, Docker image). This walks the environment it runs
in and emits one file with every dependency's declared license plus the verbatim
LICENSE / NOTICE / COPYING text shipped in its dist-info.

Stdlib-only on purpose: it must run inside the throwaway build venvs (build_win.ps1
/ build_mac.sh) and the Docker image, which do NOT install the dev dependency
group. Run it against the *same* interpreter that is being packaged so it lists
exactly the bundled packages.

Usage:
    python scripts/generate_third_party_licenses.py [OUTPUT_PATH]

Defaults OUTPUT_PATH to ./THIRD_PARTY_LICENSES.txt.
"""
from __future__ import annotations

import sys
from importlib import metadata
from pathlib import Path

# Files inside a dist-info that carry attribution text worth reproducing.
_LICENSE_PREFIXES = ("license", "licence", "copying", "notice", "authors")

# Our own package — no need to attribute ourselves in the third-party file.
_SELF = {"aespa"}


def _license_id(md: metadata.PackageMetadata) -> str:
    """Best-effort single-line license identifier from package metadata."""
    expr = (md.get("License-Expression") or "").strip()
    if expr:
        return expr
    classifiers = [
        v.split("::")[-1].strip()
        for k, v in md.items()
        if k == "Classifier" and v.startswith("License ")
    ]
    if classifiers:
        return "; ".join(classifiers)
    lic = (md.get("License") or "").strip()
    if lic:
        # Some packages dump the whole license text into this field; keep line 1.
        return lic.splitlines()[0][:80]
    return "UNKNOWN"


def _license_texts(dist: metadata.Distribution) -> list[tuple[str, str]]:
    """Return (filename, text) for LICENSE/NOTICE/COPYING files in the dist-info."""
    out: list[tuple[str, str]] = []
    # Filenames the package explicitly declares as license files (METADATA 2.4).
    declared = {p.split("/")[-1].lower() for p in (dist.metadata.get_all("License-File") or [])}
    seen: set[str] = set()
    for f in dist.files or []:
        name = f.name.lower()
        # Only pull files that live inside the package's own dist-info/egg-info
        # tree (root OR a licenses/ subdir), to avoid grabbing unrelated LICENSE
        # files from vendored subpackages.
        in_metadata_dir = any(
            part.lower().endswith((".dist-info", ".egg-info")) for part in f.parts
        )
        if not in_metadata_dir:
            continue
        if not (name.startswith(_LICENSE_PREFIXES) or name in declared):
            continue
        if name in seen:
            continue
        seen.add(name)
        try:
            text = f.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            try:
                text = Path(dist.locate_file(f)).read_text(
                    encoding="utf-8", errors="replace"
                )
            except OSError:
                continue
        out.append((f.name, text.strip()))
    return out


def main() -> int:
    out_path = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("THIRD_PARTY_LICENSES.txt")
    out_path.parent.mkdir(parents=True, exist_ok=True)

    dists: dict[str, metadata.Distribution] = {}
    for dist in metadata.distributions():
        name = dist.metadata["Name"]
        if not name or name.lower() in _SELF:
            continue
        # Deduplicate (an env can expose the same dist twice).
        dists.setdefault(name.lower(), dist)

    lines: list[str] = []
    lines.append("THIRD-PARTY SOFTWARE LICENSES")
    lines.append("=" * 78)
    lines.append("")
    lines.append(
        "AESPA is distributed with the following third-party Python packages. "
        "Each is\nprovided under its own license, reproduced below. This file is "
        "generated by\nscripts/generate_third_party_licenses.py."
    )
    lines.append("")

    # Summary table first.
    lines.append("SUMMARY")
    lines.append("-" * 78)
    for key in sorted(dists):
        d = dists[key]
        lines.append(f"  {d.metadata['Name']} {d.version} — {_license_id(d.metadata)}")
    lines.append("")
    lines.append("=" * 78)
    lines.append("")

    missing: list[str] = []
    for key in sorted(dists):
        d = dists[key]
        name = d.metadata["Name"]
        lines.append(f"{name} {d.version}")
        lines.append(f"License: {_license_id(d.metadata)}")
        texts = _license_texts(d)
        if texts:
            for fname, text in texts:
                lines.append("")
                lines.append(f"----- {fname} -----")
                lines.append(text)
        else:
            missing.append(name)
            lines.append("")
            lines.append(
                "(No license file was shipped in this package's metadata. "
                "See the license\nidentifier above and the project's page on "
                "https://pypi.org/ for full terms.)"
            )
        lines.append("")
        lines.append("=" * 78)
        lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")

    print(f"Wrote {out_path} covering {len(dists)} packages.")
    if missing:
        print(
            f"Note: {len(missing)} package(s) shipped no embedded license file "
            "(identifier only): " + ", ".join(sorted(missing))
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
