export const api = {
  listSites:        ()            => req("/api/sites"),
  getSite:          (id)          => req(`/api/sites/${id}`),
  createSite:       (b)           => req("/api/sites",         { method:"POST",   body:b }),
  updateSite:       (id,b)        => req(`/api/sites/${id}`,   { method:"PUT",    body:b }),
  deleteSite:       (id)          => req(`/api/sites/${id}`,   { method:"DELETE" }),
  importSite:       (text)        => fetch("/api/sites/import", { method:"POST", headers:{"Content-Type":"application/json"}, body:text }).then(async r => { const d = r.ok ? await r.json() : (() => { throw new Error(`Import failed: ${r.status}`); })(); return d; }),
  listApiCollections:  ()         => req("/api/api-collections"),
  getApiCollection:    (id)       => req(`/api/api-collections/${id}`),
  createApiCollection: (b)        => req("/api/api-collections",       { method:"POST",   body:b }),
  updateApiCollection: (id,b)     => req(`/api/api-collections/${id}`, { method:"PUT",    body:b }),
  deleteApiCollection: (id)       => req(`/api/api-collections/${id}`, { method:"DELETE" }),
  importApiCollection: (text)     => fetch("/api/api-collections/import", { method:"POST", headers:{"Content-Type":"application/json"}, body:text }).then(async r => { if (!r.ok) throw new Error(`Import failed: ${r.status}`); return r.json(); }),
  listApiDocuments:    (id)       => req(`/api/api-collections/${id}/documents`),
  uploadApiDocuments:  (id,files) => {
    const fd = new FormData();
    for (const f of files) fd.append("files", f);
    return fetch(`/api/api-collections/${id}/documents`, { method:"POST", body:fd })
      .then(async r => { const t = await r.text(); const d = t?JSON.parse(t):null; if(!r.ok){ const e=new Error(formatError(d)||`${r.status} ${r.statusText}`); e.status=r.status; throw e; } return d; });
  },
  downloadApiDocument: (id,docId) => { window.location.href = `/api/api-collections/${id}/documents/${docId}/download`; },
  deleteApiDocument:   (id,docId) => req(`/api/api-collections/${id}/documents/${docId}`, { method:"DELETE" }),
  parseApiDocument:    (id,docId) => req(`/api/api-collections/${id}/documents/${docId}/parse`, { method:"POST" }),
  listApiEndpoints:    (id)       => req(`/api/api-collections/${id}/endpoints`),
  patchEndpointScope:  (id,eid,b) => req(`/api/api-collections/${id}/endpoints/${eid}/scope`, { method:"PATCH", body:b }),
  listApiCredentials:  (id)       => req(`/api/api-collections/${id}/credentials`),
  createApiCredential: (id,b)     => req(`/api/api-collections/${id}/credentials`, { method:"POST", body:b }),
  deleteApiCredential: (id,cid)   => req(`/api/api-collections/${id}/credentials/${cid}`, { method:"DELETE" }),
  getApiReadiness:     (id)       => req(`/api/api-collections/${id}/readiness`),
  runApiReadiness:     (id)       => req(`/api/api-collections/${id}/readiness`, { method:"POST" }),
  purgeCollectionData: (id)       => req(`/api/api-collections/${id}/data`, { method:"DELETE" }),
  listApiRuns:         (id)       => req(`/api/api-collections/${id}/test-runs`),
  createApiRun:        (id,b)     => req(`/api/api-collections/${id}/test-runs`, { method:"POST", body:b }),
  getApiRun:           (id)       => req(`/api/api-test-runs/${id}`),
  deleteApiRun:        (id)       => req(`/api/api-test-runs/${id}`, { method:"DELETE" }),
  getApiAliceSessions: (id)       => req(`/api/api-test-runs/${id}/alice/sessions`),
  saveApiAliceSessions:(id,b)     => req(`/api/api-test-runs/${id}/alice/sessions`, { method:"PUT", body:b }),
  getApiAliceStatus:   (id)       => req(`/api/api-test-runs/${id}/alice/status`),
  startApiAliceRun:    (id,b)     => req(`/api/api-test-runs/${id}/alice/run`,      { method:"POST", body:b }),
  stopApiAliceRun:     (id)       => req(`/api/api-test-runs/${id}/alice/run`,      { method:"DELETE" }),
  getApiAgentLog:      (id)       => req(`/api/api-test-runs/${id}/agent-log`),
  clearApiAgentLog:    (id)       => req(`/api/api-test-runs/${id}/agent-log`,     { method:"DELETE" }),
  startApiScan:        (id, coverageMode) => req(`/api/api-test-runs/${id}/scan/start`, { method:"POST", body: coverageMode ? { coverage_mode: coverageMode } : undefined }),
  stopApiScan:         (id)       => req(`/api/api-test-runs/${id}/scan/stop`,     { method:"POST" }),
  getApiScanStatus:    (id)       => req(`/api/api-test-runs/${id}/scan/status`),
  getApiFindings:      (id)       => req(`/api/api-test-runs/${id}/findings`),
  clearApiFindings:    (id)       => req(`/api/api-test-runs/${id}/findings`,      { method:"DELETE" }),
  deleteApiFinding:    (id,fid)   => req(`/api/api-test-runs/${id}/findings/${fid}`, { method:"DELETE" }),
  updateApiFinding:    (id,fid,b) => req(`/api/api-test-runs/${id}/findings/${fid}`, { method:"PATCH", body:b }),
  importApiFindings:   (id,b)     => req(`/api/api-test-runs/${id}/findings/import`, { method:"POST", body:b }),
  getApiTraffic:       (id,since) => req(`/api/api-test-runs/${id}/traffic${since?`?since_id=${since}`:"" }`),
  getApiTrafficCount:  (id)       => req(`/api/api-test-runs/${id}/traffic/count`),
  getApiCoverageMatrix:(id)       => req(`/api/api-test-runs/${id}/coverage`),
  getWebCoverageMatrix:(id)       => req(`/api/test-runs/${id}/coverage`),
  seedWebWorkprogram:  (id)       => req(`/api/test-runs/${id}/coverage/seed`, { method:"POST" }),
  getApiRunLeads:      (id)       => req(`/api/api-test-runs/${id}/leads`),
  getApiRunAvailableSastRuns: (id) => req(`/api/api-test-runs/${id}/sast-runs/available`),
  importApiSastLeads:  (id,b)     => req(`/api/api-test-runs/${id}/import-leads`, { method:"POST", body:b }),
  clearApiRunLeads:    (id)       => req(`/api/api-test-runs/${id}/leads`, { method:"DELETE" }),
  deleteApiRunLead:    (id,lid)   => req(`/api/api-test-runs/${id}/leads/${lid}`, { method:"DELETE" }),
  // SAST runs
  listAllSastRuns:     ()         => req(`/api/sast-runs`),
  getSastScanLog:      (id)       => req(`/api/sast-runs/${id}/scan-log`),
  getSastRun:          (id)       => req(`/api/sast-runs/${id}`),
  deleteSastRun:       (id)       => req(`/api/sast-runs/${id}`, { method:"DELETE" }),
  startSastScan:       (id)       => req(`/api/sast-runs/${id}/scan/start`, { method:"POST" }),
  stopSastScan:        (id)       => req(`/api/sast-runs/${id}/scan/stop`,  { method:"POST" }),
  getSastScanStatus:   (id)       => req(`/api/sast-runs/${id}/scan/status`),
  getSastAgentLog:     (id)       => req(`/api/sast-runs/${id}/agent-log`),
  getSastLeads:        (id)       => req(`/api/sast-runs/${id}/leads`),
  createStandaloneSastRun: (file, name) => {
    const fd = new FormData();
    fd.append("file", file);
    if (name) fd.append("name", name);
    return fetch(`/api/sast-runs`, { method:"POST", body:fd })
      .then(async r => { const t = await r.text(); const d = t?JSON.parse(t):null; if(!r.ok){ const e=new Error(formatError(d)||`${r.status} ${r.statusText}`); e.status=r.status; throw e; } return d; });
  },
  // SAST leads imported into a web run
  getRunAvailableSastRuns: (id)   => req(`/api/test-runs/${id}/sast-runs/available`),
  importSastLeads:     (id,b)     => req(`/api/test-runs/${id}/import-leads`, { method:"POST", body:b }),
  getRunLeads:         (id)       => req(`/api/test-runs/${id}/leads`),
  clearRunLeads:       (id)       => req(`/api/test-runs/${id}/leads`, { method:"DELETE" }),
  deleteRunLead:       (id,lid)   => req(`/api/test-runs/${id}/leads/${lid}`, { method:"DELETE" }),
  getLLMConfig:     ()            => req("/api/settings/llm"),
  upsertLLMConfig:  (b)           => req("/api/settings/llm",  { method:"PUT",    body:b }),
  listLLMModels:    ()            => req("/api/settings/llm/model-configs"),
  createLLMModel:   (b)           => req("/api/settings/llm/model-configs", { method:"POST", body:b }),
  updateLLMModel:   (id,b)        => req(`/api/settings/llm/model-configs/${id}`, { method:"PUT", body:b }),
  activateLLMModel: (id)          => req(`/api/settings/llm/model-configs/${id}/activate`, { method:"POST" }),
  deleteLLMModel:   (id)          => req(`/api/settings/llm/model-configs/${id}`, { method:"DELETE" }),
  listLLMProfiles:  ()            => req("/api/settings/llm/profiles"),
  createLLMProfile: (b)           => req("/api/settings/llm/profiles", { method:"POST", body:b }),
  updateLLMProfile: (id,b)        => req(`/api/settings/llm/profiles/${id}`, { method:"PUT", body:b }),
  activateLLMProfile: (id)        => req(`/api/settings/llm/profiles/${id}/activate`, { method:"POST" }),
  deleteLLMProfile: (id)          => req(`/api/settings/llm/profiles/${id}`, { method:"DELETE" }),
  listLLMProviders: ()            => req("/api/settings/llm/providers"),
  createLLMProvider: (b)          => req("/api/settings/llm/providers", { method:"POST", body:b }),
  updateLLMProvider: (id,b)       => req(`/api/settings/llm/providers/${id}`, { method:"PUT", body:b }),
  deleteLLMProvider: (id)         => req(`/api/settings/llm/providers/${id}`, { method:"DELETE" }),
  exportLLMConfig:  ()            => req("/api/settings/llm/export"),
  importLLMConfig:  (b)           => req("/api/settings/llm/import", { method:"POST", body:b }),
  getDefaultModels: ()            => req("/api/settings/llm/models"),
  getScannerPolicy: ()            => req("/api/settings/scanner-policy"),
  upsertScannerPolicy: (b)        => req("/api/settings/scanner-policy", { method:"PUT", body:b }),
  getBurpRestApiConfig: ()        => req("/api/settings/burp-rest-api"),
  upsertBurpRestApiConfig: (b)    => req("/api/settings/burp-rest-api", { method:"PUT", body:b }),
  testBurpConnection: ()          => req("/api/settings/burp-rest-api/test-connection", { method:"POST" }),
  getUpstreamProxy: ()            => req("/api/settings/upstream-proxy"),
  upsertUpstreamProxy: (b)        => req("/api/settings/upstream-proxy", { method:"PUT", body:b }),
  getSpecialistAgentConfig: ()    => req("/api/settings/specialist-agent-config"),
  upsertSpecialistAgentConfig:(b) => req("/api/settings/specialist-agent-config", { method:"PUT", body:b }),
  getAdversarialValidatorConfig: ()    => req("/api/settings/adversarial-validator-config"),
  upsertAdversarialValidatorConfig:(b) => req("/api/settings/adversarial-validator-config", { method:"PUT", body:b }),
  getGlobalHttpHeader: ()         => req("/api/settings/global-http-header"),
  upsertGlobalHttpHeader: (b)     => req("/api/settings/global-http-header", { method:"PUT", body:b }),
  getReportingDebugConfig: ()     => req("/api/settings/reporting-debug"),
  upsertReportingDebugConfig:(b)  => req("/api/settings/reporting-debug", { method:"PUT", body:b }),
  getCloudflareAccessConfig: ()   => req("/api/settings/cloudflare-access"),
  upsertCloudflareAccessConfig:(b)=> req("/api/settings/cloudflare-access", { method:"PUT", body:b }),
  getReportingDebugPrompt: (key)  => req(`/api/reporting-debug/prompt${key?`?key=${encodeURIComponent(key)}`:""}`),
  listReportingDebugPrompts:()    => req("/api/reporting-debug/prompts"),
  saveReportingDebugPrompt:(key,b)=> req(`/api/reporting-debug/prompt?key=${encodeURIComponent(key)}`, { method:"PUT", body:b }),
  resetReportingDebugPrompt:(key) => req(`/api/reporting-debug/prompt/reset?key=${encodeURIComponent(key)}`, { method:"POST" }),
  listReportingPromptVersions:(key)=> req(`/api/reporting-debug/prompt-versions?key=${encodeURIComponent(key)}`),
  createReportingPromptVersion:(b)=> req("/api/reporting-debug/prompt-versions", { method:"POST", body:b }),
  updateReportingPromptVersion:(id,b)=> req(`/api/reporting-debug/prompt-versions/${id}`, { method:"PUT", body:b }),
  deleteReportingPromptVersion:(id)=> req(`/api/reporting-debug/prompt-versions/${id}`, { method:"DELETE" }),
  listReportingCaptures: ()       => req("/api/reporting-debug/captures"),
  getReportingCapture:(id)         => req(`/api/reporting-debug/captures/${id}`),
  replayReportingCapture:(id,b={})=> req(`/api/reporting-debug/captures/${id}/replay`, { method:"POST", body:b }),
  getReportingReplay:(id)         => req(`/api/reporting-debug/replays/${id}`),
  listReportingReplays:()         => req("/api/reporting-debug/replays"),
  listActiveJobs:    ()            => req("/api/test-runs/active"),
  listRuns:         (siteId)      => req(`/api/sites/${siteId}/test-runs`),
  createRun:        (siteId,b)    => req(`/api/sites/${siteId}/test-runs`, { method:"POST", body:b }),
  getRun:           (id)          => req(`/api/test-runs/${id}`),
  deleteRun:        (id)          => req(`/api/test-runs/${id}`,  { method:"DELETE" }),
  startRun:         (id)          => req(`/api/test-runs/${id}/start`,   { method:"POST" }),
  stopRun:          (id)          => req(`/api/test-runs/${id}/stop`,    { method:"POST" }),
  restartRun:       (id)          => req(`/api/test-runs/${id}/restart`, { method:"POST" }),
  clearCrawl:       (id)          => req(`/api/test-runs/${id}/crawl/clear`, { method:"POST" }),
  exportCrawl:      (id)          => { window.location.href = `/api/test-runs/${id}/crawl/export`; },
  importCrawl:      (id,file)     => {
    const fd = new FormData();
    fd.append("file", file);
    return fetch(`/api/test-runs/${id}/crawl/import`, { method:"POST", body:fd })
      .then(async r => { const t = await r.text(); const d = t ? JSON.parse(t) : null; if (!r.ok) throw new Error(formatError(d) || `${r.status} ${r.statusText}`); return d; });
  },
  getGraph:         (id)          => req(`/api/test-runs/${id}/graph`),
  listPages:        (id)          => req(`/api/test-runs/${id}/pages`),
  getPage:          (runId,pgId)  => req(`/api/test-runs/${runId}/pages/${pgId}`),
  getPageViews:     (runId,pgId)  => req(`/api/test-runs/${runId}/pages/${pgId}/views`),
  getTargetIntelligence: (id,kind="") => req(`/api/test-runs/${id}/target-intelligence${kind?`?kind=${encodeURIComponent(kind)}`:""}`),
  getScannerSessions: (id, includeInactive=true) => req(`/api/test-runs/${id}/scanner-sessions${includeInactive?"?include_inactive=true":""}`),
  updateScannerSession: (runId, sessionId, b) => req(`/api/test-runs/${runId}/scanner-sessions/${sessionId}`, { method:"PATCH", body:b }),
  getApiScannerSessions: (id, includeInactive=true) => req(`/api/api-test-runs/${id}/scanner-sessions${includeInactive?"?include_inactive=true":""}`),
  updateApiScannerSession: (runId, sessionId, b) => req(`/api/api-test-runs/${runId}/scanner-sessions/${sessionId}`, { method:"PATCH", body:b }),
  getReconSummary:  (id)          => req(`/api/test-runs/${id}/recon-summary`),
  setPageScope:     (runId,pgId,b)=> req(`/api/test-runs/${runId}/pages/${pgId}/scope`, { method:"PATCH", body:b }),
  updateScopeHosts: (siteId, hosts) => req(`/api/sites/${siteId}/scope-hosts`, { method:"PUT", body:{scope_hosts:hosts} }),
  deletePage:       (runId,pgId,cascade) => req(`/api/test-runs/${runId}/pages/${pgId}?cascade=${cascade}`, { method:"DELETE" }),
  updateRun:        (id,b)        => req(`/api/test-runs/${id}`,                         { method:"PATCH", body:b }),
  startThinkingScan:(id, coverageMode) => req(`/api/test-runs/${id}/thinking-scan/start`, { method:"POST", body: coverageMode ? { coverage_mode: coverageMode } : undefined }),
  resumeThinkingScan:(id)         => req(`/api/test-runs/${id}/thinking-scan/resume`,     { method:"POST" }),
  stopThinkingScan: (id)          => req(`/api/test-runs/${id}/thinking-scan/stop`,       { method:"POST" }),
  getThinkingStatus:(id)          => req(`/api/test-runs/${id}/thinking-scan/status`),
  getCheckpointStatus:(id)        => req(`/api/test-runs/${id}/thinking-scan/checkpoint`),
  getScanLog:        (id)          => req(`/api/test-runs/${id}/scan-log`),
  getAgentLog:       (id)          => req(`/api/test-runs/${id}/agent-log`),
  getTokenUsage:     (id)          => req(`/api/test-runs/${id}/token-usage`),
  getAliceSessions:  (id)          => req(`/api/test-runs/${id}/alice/sessions`),
  saveAliceSessions: (id, b)       => req(`/api/test-runs/${id}/alice/sessions`, { method:"PUT", body:b }),
  getAliceStatus:    (id)          => req(`/api/test-runs/${id}/alice/status`),
  startAliceRun:     (id, b)       => req(`/api/test-runs/${id}/alice/run`,      { method:"POST", body:b }),
  stopAliceRun:      (id)          => req(`/api/test-runs/${id}/alice/run`,      { method:"DELETE" }),
  getFindings:           (id)       => req(`/api/test-runs/${id}/findings`),
  deleteFinding:         (id,fid)   => req(`/api/test-runs/${id}/findings/${fid}`, { method:"DELETE" }),
  updateFinding:         (id,fid,b) => req(`/api/test-runs/${id}/findings/${fid}`, { method:"PATCH", body:b }),
  deleteFindingGroup:    (id,title) => req(`/api/test-runs/${id}/findings?title=${encodeURIComponent(title)}`, { method:"DELETE" }),
  importFindings:        (id,b)     => req(`/api/test-runs/${id}/findings/import`, { method:"POST", body:b }),
  validateAllFindings:   (id)       => req(`/api/test-runs/${id}/validate`, { method:"POST" }),
  validateFinding:       (id,fid)   => req(`/api/test-runs/${id}/findings/${fid}/validate`, { method:"POST" }),
  stopValidation:        (id)       => req(`/api/test-runs/${id}/validate/stop`, { method:"POST" }),
  getValidateStatus:     (id)       => req(`/api/test-runs/${id}/validate/status`),
  getTraffic:       (id,since)    => req(`/api/test-runs/${id}/traffic?since_id=${since||0}`),
  getTrafficCount:  (id)          => req(`/api/test-runs/${id}/traffic/count`),
  clearTraffic:         (id)       => req(`/api/test-runs/${id}/traffic`,               { method:"DELETE" }),
  clearFindings:        (id)       => req(`/api/test-runs/${id}/findings`,              { method:"DELETE" }),
  clearScanLog:         (id)       => req(`/api/test-runs/${id}/scan-log`,              { method:"DELETE" }),
  clearTargetIntel:     (id)       => req(`/api/test-runs/${id}/target-intelligence`,   { method:"DELETE" }),
  getVersion:       ()            => req("/api/version"),
};

export async function req(url, opts = {}) {
  const init = { method: opts.method || "GET", headers: { "Content-Type": "application/json" } };
  if (opts.body !== undefined) init.body = JSON.stringify(opts.body);
  const res  = await fetch(url, init);
  if (res.status === 204) return null;
  const text = await res.text();
  const data = text ? JSON.parse(text) : null;
  if (!res.ok) {
    const msg = formatError(data) || `${res.status} ${res.statusText}`;
    const err = new Error(msg); err.status = res.status; throw err;
  }
  return data;
}

export function formatError(d) {
  if (!d) return null;
  if (typeof d.detail === "string") return d.detail;
  if (Array.isArray(d.detail)) return d.detail.map(x => `${(x.loc||[]).join(".")}: ${x.msg}`).join("\n");
  return JSON.stringify(d);
}
